version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.99.3 # host docker ip
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  ####################################
  # Schema Registry
  ####################################
  schemaregistry:
    image: confluentinc/cp-schema-registry:5.5.1
    container_name: schemaregistry
    restart: always
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8085:8085
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
  ####################################
  # App
  ####################################
  todo_app:
    container_name: todo_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - schemaregistry
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - spring.kafka.properties.schema-registry-url=schemaregistry:8085